export const enum ERROR_CODE {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',

  // Verification
  VERIFY_CODE_NOT_FOUND = 'VERIFY_CODE_NOT_FOUND',
  VERIFY_CODE_EXPIRED = 'VERIFY_CODE_EXPIRED',
  VERIFY_TOO_MANY_ATTEMPTS = 'VERIFY_TOO_MANY_ATTEMPTS',
  VERIFY_INVALID_CODE = 'VERIFY_INVALID_CODE',

  // Roles management
  ROLES_INVALID_PERMISSIONS = 'ROLES_INVALID_PERMISSIONS',
  ROLES_CANNOT_MODIFY_SYSTEM_ROLE = 'ROLES_CANNOT_MODIFY_SYSTEM_ROLE',
  ROLES_CANNOT_DELETE_SYSTEM_ROLE = 'ROLES_CANNOT_DELETE_SYSTEM_ROLE',
  ROLES_CANNOT_DELETE_WITH_USERS = 'ROLES_CANNOT_DELETE_WITH_USERS',

  // Generic
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}